name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate Version
      id: version_number
      run: echo "num=$(date +%s)" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tannerk/hoursoutsideapi:${{ steps.version_number.outputs.num }}

    - name: Login to Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u tannerk --password-stdin

    - name: Push to Docker
      run: docker push tannerk/hoursoutsideapi:${{ steps.version_number.outputs.num }}
      
